# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='UserProfile',
        ),
    ]
